// Lista de serviços anexa à Lei Complementar 116/2003 (com redações posteriores
// aplicadas — LC 157/2016, LC 175/2020, LC 183/2021). Fonte: planalto.gov.br.
// Usada para o picker de "Item da Lista de Serviço" na emissão de NFS-e.
export interface Lc116Item {
  codigo: string
  descricao: string
  grupo: string
}

export const LC116_ITENS: Lc116Item[] = [
  { codigo: '1.01', grupo: 'Serviços de informática e congêneres', descricao: 'Análise e desenvolvimento de sistemas.' },
  { codigo: '1.02', grupo: 'Serviços de informática e congêneres', descricao: 'Programação.' },
  { codigo: '1.03', grupo: 'Serviços de informática e congêneres', descricao: 'Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres.' },
  { codigo: '1.04', grupo: 'Serviços de informática e congêneres', descricao: 'Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets, smartphones e congêneres.' },
  { codigo: '1.05', grupo: 'Serviços de informática e congêneres', descricao: 'Licenciamento ou cessão de direito de uso de programas de computação.' },
  { codigo: '1.06', grupo: 'Serviços de informática e congêneres', descricao: 'Assessoria e consultoria em informática.' },
  { codigo: '1.07', grupo: 'Serviços de informática e congêneres', descricao: 'Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados.' },
  { codigo: '1.08', grupo: 'Serviços de informática e congêneres', descricao: 'Planejamento, confecção, manutenção e atualização de páginas eletrônicas.' },
  { codigo: '1.09', grupo: 'Serviços de informática e congêneres', descricao: 'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet.' },
  { codigo: '2.01', grupo: 'Pesquisas e desenvolvimento', descricao: 'Serviços de pesquisas e desenvolvimento de qualquer natureza.' },
  { codigo: '3.02', grupo: 'Locação, cessão de direito de uso e congêneres', descricao: 'Cessão de direito de uso de marcas e de sinais de propaganda.' },
  { codigo: '3.03', grupo: 'Locação, cessão de direito de uso e congêneres', descricao: 'Exploração de salões de festas, centro de convenções, escritórios virtuais, stands, quadras esportivas e congêneres, para realização de eventos ou negócios de qualquer natureza.' },
  { codigo: '3.04', grupo: 'Locação, cessão de direito de uso e congêneres', descricao: 'Locação, sublocação, arrendamento, direito de passagem ou permissão de uso de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza.' },
  { codigo: '3.05', grupo: 'Locação, cessão de direito de uso e congêneres', descricao: 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.' },
  { codigo: '4.01', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Medicina e biomedicina.' },
  { codigo: '4.02', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres.' },
  { codigo: '4.03', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres.' },
  { codigo: '4.04', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Instrumentação cirúrgica.' },
  { codigo: '4.05', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Acupuntura.' },
  { codigo: '4.06', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Enfermagem, inclusive serviços auxiliares.' },
  { codigo: '4.07', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Serviços farmacêuticos.' },
  { codigo: '4.08', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Terapia ocupacional, fisioterapia e fonoaudiologia.' },
  { codigo: '4.09', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental.' },
  { codigo: '4.10', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Nutrição.' },
  { codigo: '4.11', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Obstetrícia.' },
  { codigo: '4.12', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Odontologia.' },
  { codigo: '4.13', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Ortóptica.' },
  { codigo: '4.14', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Próteses sob encomenda.' },
  { codigo: '4.15', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Psicanálise.' },
  { codigo: '4.16', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Psicologia.' },
  { codigo: '4.17', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Casas de repouso e de recuperação, creches, asilos e congêneres.' },
  { codigo: '4.18', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Inseminação artificial, fertilização in vitro e congêneres.' },
  { codigo: '4.19', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres.' },
  { codigo: '4.20', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie.' },
  { codigo: '4.21', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Unidade de atendimento, assistência ou tratamento móvel e congêneres.' },
  { codigo: '4.22', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres.' },
  { codigo: '4.23', grupo: 'Saúde, assistência médica e congêneres', descricao: 'Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário.' },
  { codigo: '5.01', grupo: 'Medicina e assistência veterinária', descricao: 'Medicina veterinária e zootecnia.' },
  { codigo: '5.02', grupo: 'Medicina e assistência veterinária', descricao: 'Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária.' },
  { codigo: '5.03', grupo: 'Medicina e assistência veterinária', descricao: 'Laboratórios de análise na área veterinária.' },
  { codigo: '5.04', grupo: 'Medicina e assistência veterinária', descricao: 'Inseminação artificial, fertilização in vitro e congêneres (veterinária).' },
  { codigo: '5.05', grupo: 'Medicina e assistência veterinária', descricao: 'Bancos de sangue e de órgãos e congêneres (veterinária).' },
  { codigo: '5.06', grupo: 'Medicina e assistência veterinária', descricao: 'Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie (veterinária).' },
  { codigo: '5.07', grupo: 'Medicina e assistência veterinária', descricao: 'Unidade de atendimento, assistência ou tratamento móvel e congêneres (veterinária).' },
  { codigo: '5.08', grupo: 'Medicina e assistência veterinária', descricao: 'Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres.' },
  { codigo: '5.09', grupo: 'Medicina e assistência veterinária', descricao: 'Planos de atendimento e assistência médico-veterinária.' },
  { codigo: '6.01', grupo: 'Cuidados pessoais, estética e atividades físicas', descricao: 'Barbearia, cabeleireiros, manicuros, pedicuros e congêneres.' },
  { codigo: '6.02', grupo: 'Cuidados pessoais, estética e atividades físicas', descricao: 'Esteticistas, tratamento de pele, depilação e congêneres.' },
  { codigo: '6.03', grupo: 'Cuidados pessoais, estética e atividades físicas', descricao: 'Banhos, duchas, sauna, massagens e congêneres.' },
  { codigo: '6.04', grupo: 'Cuidados pessoais, estética e atividades físicas', descricao: 'Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas.' },
  { codigo: '6.05', grupo: 'Cuidados pessoais, estética e atividades físicas', descricao: 'Centros de emagrecimento, spa e congêneres.' },
  { codigo: '6.06', grupo: 'Cuidados pessoais, estética e atividades físicas', descricao: 'Aplicação de tatuagens, piercings e congêneres.' },
  { codigo: '7.01', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres.' },
  { codigo: '7.02', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes (exceto fornecimento de mercadorias produzidas pelo prestador fora do local, sujeito a ICMS).' },
  { codigo: '7.03', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Elaboração de planos diretores, estudos de viabilidade, projetos básicos e executivos para trabalhos de engenharia.' },
  { codigo: '7.04', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Demolição.' },
  { codigo: '7.05', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.' },
  { codigo: '7.06', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres, com material fornecido pelo tomador.' },
  { codigo: '7.07', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Recuperação, raspagem, polimento e lustração de pisos e congêneres.' },
  { codigo: '7.08', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Calafetação.' },
  { codigo: '7.09', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.' },
  { codigo: '7.10', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.' },
  { codigo: '7.11', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Decoração e jardinagem, inclusive corte e poda de árvores.' },
  { codigo: '7.12', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.' },
  { codigo: '7.13', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres.' },
  { codigo: '7.16', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal e congêneres.' },
  { codigo: '7.17', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Escoramento, contenção de encostas e serviços congêneres.' },
  { codigo: '7.18', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.' },
  { codigo: '7.19', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.' },
  { codigo: '7.20', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Aerofotogrametria (inclusive interpretação), cartografia, mapeamento, levantamentos topográficos, batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres.' },
  { codigo: '7.21', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Pesquisa, perfuração, cimentação, mergulho, perfilagem e outros serviços relacionados com a exploração de petróleo, gás natural e outros recursos minerais.' },
  { codigo: '7.22', grupo: 'Engenharia, arquitetura, construção civil e congêneres', descricao: 'Nucleação e bombardeamento de nuvens e congêneres.' },
  { codigo: '8.01', grupo: 'Educação, ensino e treinamento', descricao: 'Ensino regular pré-escolar, fundamental, médio e superior.' },
  { codigo: '8.02', grupo: 'Educação, ensino e treinamento', descricao: 'Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza.' },
  { codigo: '9.01', grupo: 'Hospedagem, turismo e viagens', descricao: 'Hospedagem de qualquer natureza em hotéis, apart-service, flat, motéis, pensões e congêneres; ocupação por temporada com fornecimento de serviço.' },
  { codigo: '9.02', grupo: 'Hospedagem, turismo e viagens', descricao: 'Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres.' },
  { codigo: '9.03', grupo: 'Hospedagem, turismo e viagens', descricao: 'Guias de turismo.' },
  { codigo: '10.01', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento, corretagem ou intermediação de câmbio, de seguros, de cartões de crédito, de planos de saúde e de planos de previdência privada.' },
  { codigo: '10.02', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer.' },
  { codigo: '10.03', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária.' },
  { codigo: '10.04', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing), de franquia (franchising) e de faturização (factoring).' },
  { codigo: '10.05', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens ou subitens.' },
  { codigo: '10.06', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento marítimo.' },
  { codigo: '10.07', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento de notícias.' },
  { codigo: '10.08', grupo: 'Intermediação e congêneres', descricao: 'Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios.' },
  { codigo: '10.09', grupo: 'Intermediação e congêneres', descricao: 'Representação de qualquer natureza, inclusive comercial.' },
  { codigo: '10.10', grupo: 'Intermediação e congêneres', descricao: 'Distribuição de bens de terceiros.' },
  { codigo: '11.01', grupo: 'Guarda, estacionamento, armazenamento e vigilância', descricao: 'Guarda e estacionamento de veículos terrestres automotores, de aeronaves e de embarcações.' },
  { codigo: '11.02', grupo: 'Guarda, estacionamento, armazenamento e vigilância', descricao: 'Vigilância, segurança ou monitoramento de bens, pessoas e semoventes.' },
  { codigo: '11.03', grupo: 'Guarda, estacionamento, armazenamento e vigilância', descricao: 'Escolta, inclusive de veículos e cargas.' },
  { codigo: '11.04', grupo: 'Guarda, estacionamento, armazenamento e vigilância', descricao: 'Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie.' },
  { codigo: '11.05', grupo: 'Guarda, estacionamento, armazenamento e vigilância', descricao: 'Serviços relacionados ao monitoramento e rastreamento a distância de veículos, cargas, pessoas e semoventes, por telefonia móvel, satélite, rádio ou qualquer outro meio.' },
  { codigo: '12.01', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Espetáculos teatrais.' },
  { codigo: '12.02', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Exibições cinematográficas.' },
  { codigo: '12.03', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Espetáculos circenses.' },
  { codigo: '12.04', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Programas de auditório.' },
  { codigo: '12.05', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Parques de diversões, centros de lazer e congêneres.' },
  { codigo: '12.06', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Boates, taxi-dancing e congêneres.' },
  { codigo: '12.07', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres.' },
  { codigo: '12.08', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Feiras, exposições, congressos e congêneres.' },
  { codigo: '12.09', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Bilhares, boliches e diversões eletrônicas ou não.' },
  { codigo: '12.10', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Corridas e competições de animais.' },
  { codigo: '12.11', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Competições esportivas ou de destreza física ou intelectual, com ou sem participação do espectador.' },
  { codigo: '12.12', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Execução de música.' },
  { codigo: '12.13', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows e congêneres.' },
  { codigo: '12.14', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo.' },
  { codigo: '12.15', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres.' },
  { codigo: '12.16', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Exibição de filmes, entrevistas, musicais, espetáculos, shows, concertos, desfiles, óperas, competições esportivas ou congêneres.' },
  { codigo: '12.17', grupo: 'Diversões, lazer, entretenimento e congêneres', descricao: 'Recreação e animação, inclusive em festas e eventos de qualquer natureza.' },
  { codigo: '13.02', grupo: 'Fonografia, fotografia, cinematografia e reprografia', descricao: 'Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres.' },
  { codigo: '13.03', grupo: 'Fonografia, fotografia, cinematografia e reprografia', descricao: 'Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres.' },
  { codigo: '13.04', grupo: 'Fonografia, fotografia, cinematografia e reprografia', descricao: 'Reprografia, microfilmagem e digitalização.' },
  { codigo: '13.05', grupo: 'Fonografia, fotografia, cinematografia e reprografia', descricao: 'Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia (exceto se destinados a posterior comercialização/industrialização, sujeitos a ICMS).' },
  { codigo: '14.01', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos e equipamentos (exceto peças, sujeitas a ICMS).' },
  { codigo: '14.02', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Assistência técnica.' },
  { codigo: '14.03', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Recondicionamento de motores (exceto peças, sujeitas a ICMS).' },
  { codigo: '14.04', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Recauchutagem ou regeneração de pneus.' },
  { codigo: '14.05', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer.' },
  { codigo: '14.06', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido.' },
  { codigo: '14.07', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Colocação de molduras e congêneres.' },
  { codigo: '14.08', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Encadernação, gravação e douração de livros, revistas e congêneres.' },
  { codigo: '14.09', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento.' },
  { codigo: '14.10', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Tinturaria e lavanderia.' },
  { codigo: '14.11', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Tapeçaria e reforma de estofamentos em geral.' },
  { codigo: '14.12', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Funilaria e lanternagem.' },
  { codigo: '14.13', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Carpintaria e serralheria.' },
  { codigo: '14.14', grupo: 'Serviços relativos a bens de terceiros', descricao: 'Guincho intramunicipal, guindaste e içamento.' },
  { codigo: '15.01', grupo: 'Setor bancário ou financeiro', descricao: 'Administração de fundos quaisquer, de consórcio, de cartão de crédito ou débito e congêneres, de carteira de clientes, de cheques pré-datados e congêneres.' },
  { codigo: '15.02', grupo: 'Setor bancário ou financeiro', descricao: 'Abertura de contas em geral, inclusive conta-corrente, conta de investimentos e caderneta de poupança, no País e no exterior, e manutenção das referidas contas.' },
  { codigo: '15.03', grupo: 'Setor bancário ou financeiro', descricao: 'Locação e manutenção de cofres particulares, de terminais eletrônicos, de terminais de atendimento e de bens e equipamentos em geral.' },
  { codigo: '15.04', grupo: 'Setor bancário ou financeiro', descricao: 'Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade e de capacidade financeira.' },
  { codigo: '15.05', grupo: 'Setor bancário ou financeiro', descricao: 'Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres, inclusão ou exclusão no CCF ou em quaisquer outros bancos cadastrais.' },
  { codigo: '15.06', grupo: 'Setor bancário ou financeiro', descricao: 'Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral; abono de firmas; coleta e entrega de documentos, bens e valores.' },
  { codigo: '15.07', grupo: 'Setor bancário ou financeiro', descricao: 'Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo, inclusive por telefone, internet e telex.' },
  { codigo: '15.08', grupo: 'Setor bancário ou financeiro', descricao: 'Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito; estudo, análise e avaliação de operações de crédito.' },
  { codigo: '15.09', grupo: 'Setor bancário ou financeiro', descricao: 'Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia e demais serviços relacionados.' },
  { codigo: '15.10', grupo: 'Setor bancário ou financeiro', descricao: 'Serviços relacionados a cobranças, recebimentos ou pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros.' },
  { codigo: '15.11', grupo: 'Setor bancário ou financeiro', descricao: 'Devolução de títulos, protesto de títulos, sustação de protesto, manutenção e reapresentação de títulos, e demais serviços relacionados.' },
  { codigo: '15.12', grupo: 'Setor bancário ou financeiro', descricao: 'Custódia em geral, inclusive de títulos e valores mobiliários.' },
  { codigo: '15.13', grupo: 'Setor bancário ou financeiro', descricao: 'Serviços relacionados a operações de câmbio em geral, edição, alteração, prorrogação, cancelamento e baixa de contrato de câmbio.' },
  { codigo: '15.14', grupo: 'Setor bancário ou financeiro', descricao: 'Fornecimento, emissão, reemissão, renovação e manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres.' },
  { codigo: '15.15', grupo: 'Setor bancário ou financeiro', descricao: 'Compensação de cheques e títulos quaisquer; serviços relacionados a depósito, inclusive depósito identificado, e a saque de contas quaisquer.' },
  { codigo: '15.16', grupo: 'Setor bancário ou financeiro', descricao: 'Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares.' },
  { codigo: '15.17', grupo: 'Setor bancário ou financeiro', descricao: 'Emissão, fornecimento, devolução, sustação, cancelamento e oposição de cheques quaisquer, avulso ou por talão.' },
  { codigo: '15.18', grupo: 'Setor bancário ou financeiro', descricao: 'Serviços relacionados a crédito imobiliário, avaliação e vistoria de imóvel ou obra, análise técnica e jurídica, emissão e reemissão de contrato.' },
  { codigo: '16.01', grupo: 'Serviços de transporte de natureza municipal', descricao: 'Serviços de transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros.' },
  { codigo: '16.02', grupo: 'Serviços de transporte de natureza municipal', descricao: 'Outros serviços de transporte de natureza municipal.' },
  { codigo: '17.01', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista; análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza.' },
  { codigo: '17.02', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Datilografia, digitação, estenografia, expediente, secretaria em geral, resposta audível, redação, edição, interpretação, revisão, tradução e congêneres.' },
  { codigo: '17.03', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa.' },
  { codigo: '17.04', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Recrutamento, agenciamento, seleção e colocação de mão-de-obra.' },
  { codigo: '17.05', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.' },
  { codigo: '17.06', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas e elaboração de desenhos, textos e demais materiais publicitários.' },
  { codigo: '17.08', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Franquia (franchising).' },
  { codigo: '17.09', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Perícias, laudos, exames técnicos e análises técnicas.' },
  { codigo: '17.10', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.' },
  { codigo: '17.11', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Organização de festas e recepções; bufê (exceto fornecimento de alimentação e bebidas, sujeito a ICMS).' },
  { codigo: '17.12', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Administração em geral, inclusive de bens e negócios de terceiros.' },
  { codigo: '17.13', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Leilão e congêneres.' },
  { codigo: '17.14', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Advocacia.' },
  { codigo: '17.15', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Arbitragem de qualquer espécie, inclusive jurídica.' },
  { codigo: '17.16', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Auditoria.' },
  { codigo: '17.17', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Análise de Organização e Métodos.' },
  { codigo: '17.18', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Atuária e cálculos técnicos de qualquer natureza.' },
  { codigo: '17.19', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Contabilidade, inclusive serviços técnicos e auxiliares.' },
  { codigo: '17.20', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Consultoria e assessoria econômica ou financeira.' },
  { codigo: '17.21', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Estatística.' },
  { codigo: '17.22', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Cobrança em geral.' },
  { codigo: '17.23', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar, relacionados a factoring.' },
  { codigo: '17.24', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Apresentação de palestras, conferências, seminários e congêneres.' },
  { codigo: '17.25', grupo: 'Apoio técnico, administrativo, jurídico, contábil, comercial', descricao: 'Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio (exceto livros, jornais, periódicos e rádio/TV livre e gratuita).' },
  { codigo: '18.01', grupo: 'Regulação de sinistros e riscos de seguros', descricao: 'Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos; prevenção e gerência de riscos seguráveis e congêneres.' },
  { codigo: '19.01', grupo: 'Loterias, bingos e apostas', descricao: 'Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, títulos de capitalização e congêneres.' },
  { codigo: '20.01', grupo: 'Serviços portuários e afins', descricao: 'Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, atracação, capatazia, armazenagem e congêneres.' },
  { codigo: '20.02', grupo: 'Serviços portuários e afins', descricao: 'Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem, capatazia, movimentação de aeronaves e congêneres.' },
  { codigo: '20.03', grupo: 'Serviços portuários e afins', descricao: 'Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros e mercadorias, logística e congêneres.' },
  { codigo: '21.01', grupo: 'Registros públicos, cartorários e notariais', descricao: 'Serviços de registros públicos, cartorários e notariais.' },
  { codigo: '22.01', grupo: 'Exploração de rodovia', descricao: 'Serviços de exploração de rodovia mediante cobrança de preço ou pedágio dos usuários, envolvendo conservação, manutenção, operação, monitoração e assistência aos usuários.' },
  { codigo: '23.01', grupo: 'Programação e comunicação visual', descricao: 'Serviços de programação e comunicação visual, desenho industrial e congêneres.' },
  { codigo: '24.01', grupo: 'Chaveiros e sinalização visual', descricao: 'Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres.' },
  { codigo: '25.01', grupo: 'Serviços funerários', descricao: 'Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo; fornecimento de flores e outros paramentos; desembaraço de certidão de óbito; embalsamento e conservação de cadáveres.' },
  { codigo: '25.02', grupo: 'Serviços funerários', descricao: 'Translado intramunicipal e cremação de corpos e partes de corpos cadavéricos.' },
  { codigo: '25.03', grupo: 'Serviços funerários', descricao: 'Planos ou convênio funerários.' },
  { codigo: '25.04', grupo: 'Serviços funerários', descricao: 'Manutenção e conservação de jazigos e cemitérios.' },
  { codigo: '25.05', grupo: 'Serviços funerários', descricao: 'Cessão de uso de espaços em cemitérios para sepultamento.' },
  { codigo: '26.01', grupo: 'Coleta, remessa ou entrega de correspondências e valores', descricao: 'Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres.' },
  { codigo: '27.01', grupo: 'Assistência social', descricao: 'Serviços de assistência social.' },
  { codigo: '28.01', grupo: 'Avaliação de bens e serviços', descricao: 'Serviços de avaliação de bens e serviços de qualquer natureza.' },
  { codigo: '29.01', grupo: 'Biblioteconomia', descricao: 'Serviços de biblioteconomia.' },
  { codigo: '30.01', grupo: 'Biologia, biotecnologia e química', descricao: 'Serviços de biologia, biotecnologia e química.' },
  { codigo: '31.01', grupo: 'Serviços técnicos em edificações e eletrônica', descricao: 'Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres.' },
  { codigo: '32.01', grupo: 'Desenhos técnicos', descricao: 'Serviços de desenhos técnicos.' },
  { codigo: '33.01', grupo: 'Desembaraço aduaneiro', descricao: 'Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres.' },
  { codigo: '34.01', grupo: 'Investigações particulares', descricao: 'Serviços de investigações particulares, detetives e congêneres.' },
  { codigo: '35.01', grupo: 'Reportagem e relações públicas', descricao: 'Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas.' },
  { codigo: '36.01', grupo: 'Meteorologia', descricao: 'Serviços de meteorologia.' },
  { codigo: '37.01', grupo: 'Artistas, atletas e modelos', descricao: 'Serviços de artistas, atletas, modelos e manequins.' },
  { codigo: '38.01', grupo: 'Museologia', descricao: 'Serviços de museologia.' },
  { codigo: '39.01', grupo: 'Ourivesaria e lapidação', descricao: 'Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço).' },
  { codigo: '40.01', grupo: 'Obras de arte sob encomenda', descricao: 'Obras de arte sob encomenda.' },
]

export function buscarLc116(termo: string): Lc116Item[] {
  const t = termo.trim().toLowerCase()
  if (!t) return LC116_ITENS
  return LC116_ITENS.filter(
    (item) => item.codigo.includes(t) || item.descricao.toLowerCase().includes(t) || item.grupo.toLowerCase().includes(t)
  )
}
